= Semantic HTML5 Backend For Asciidoctor
// custom
:gem-name: asciidoctor-html5s
:gh-name: jirutka/{gem-name}
:gh-branch: master

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}[Build Status, link="https://travis-ci.org/{gh-name}"]
image:https://img.shields.io/gem/v/{gem-name}.svg?style=flat[Gem Version, link="https://rubygems.org/gems/{gem-name}"]
image:https://img.shields.io/npm/v/{gem-name}.svg?style=flat[npm Version, link="https://www.npmjs.org/package/{gem-name}"]
endif::env-github[]

This project provides alternative HTML5 converter (backend) for http://asciidoctor.org/[Asciidoctor] that focuses on correct semantics, accessibility and compatibility with common typographic CSS styles.


== Goals

* Clean markup with correct HTML5 semantics.
* Good accessibility for people with disabilities.
* Compatibility with common typographic CSS styles when possible and especially with GitHub and GitLab.
* Full standalone converter without fallback to the built-in Asciidoctor converters.
* Easy to use and integrate into third-party projects.
* Well readable and maintainable code – this should be never sacrificed for performance (I’m looking at you, Asciidoctor!).


== Non-goals

* Compatibility with existing Asciidoctor CSS styles.


== Requirements

* https://www.ruby-lang.org/[Ruby] 2.0+, http://jruby.org/[JRuby] 9.1+ or https://nodejs.org/[Node.js]
* https://rubygems.org/gems/asciidoctor/[Asciidoctor] 1.5.5+ or https://www.npmjs.com/package/asciidoctor.js[asciidoctor.js] 1.5.5
* https://rubygems.org/gems/thread_safe/[thread_safe] (not required, but recommended for Ruby MRI)

Note: This converter consists of https://github.com/slim-template/slim/[Slim] templates, but they are precompiled into pure Ruby code using https://github.com/jirutka/asciidoctor-templates-compiler/[asciidoctor-templates-compiler], so you don’t need Slim to use it!


== Installation

=== Ruby

Install {gem-name} from Rubygems:

[source, sh, subs="+attributes"]
gem install {gem-name}

or to get the latest development version:

[source, sh, subs="+attributes"]
gem install --pre {gem-name}


=== Node.js

Install {gem-name} from npmjs.com:

[source, sh, subs="+attributes"]
npm install --save {gem-name}


== Usage

=== CLI

[source, sh, subs="+attributes"]
asciidoctor -r {gem-name} -b html5s FILE...


=== Node.js

[source, js, subs="+attributes"]
----
// Load asciidoctor.js and {gem-name}.
const asciidoctor = require('asciidoctor.js')()
const asciidoctorHtml5s = require('{gem-name}')

// Register the HTML5s converter and supporting extension.
asciidoctorHtml5s.register()

// Convert the content to HTML using html5s converter.
const content = "Hello, *world!*!"
const html = asciidoctor.convert(content, { backend: 'html5s' })
console.log(html)
----


=== Attributes

Extra attributes accepted by the {gem-name}:

html5s-force-stem-type::
  Ignore declared (e.g. `:stem: asciimath`, `asciimath:[]`, ...) and default type of the stem macro/block and always use the one specified by this attribute. +
  Asciidoctor hard-codes the default stem type to “asciimath”, which is not supported by KaTeX.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.

